In [3]:
import numpy as np
import torch
from torch.autograd import Variable
import torch.nn.functional as F
import matplotlib.pyplot as plt

In [4]:
alpha = np.array([[1, 2, -3, 0, 1, -3], 
                  [3, 1, 2, 1, 0, 2], 
                  [2, 2, 2, 2, 2, 1], 
                  [1, 0, 2, 1, -2, 2]])


beta = np.array([[1, 2, -2, 1], 
                 [1, -1, 1, 2], 
                 [3, 1, -1, 1]])


x = np.array([1, 1, 0, 0, 1, 1])

y = np.array([0, 1, 0])

In [5]:
tensor_alpha = Variable(torch.DoubleTensor(alpha), requires_grad=True)
tensor_beta = Variable(torch.DoubleTensor(beta), requires_grad=True)
tensor_x = torch.DoubleTensor(x.reshape(x.shape[0], 1))
tensor_y = torch.DoubleTensor(y.reshape(y.shape[0], 1))
tensor_bias1 = Variable(torch.DoubleTensor(np.ones((4,1))), requires_grad=True)
tensor_bias2 = Variable(torch.DoubleTensor(np.ones((3,1))), requires_grad=True)

a = torch.mm(tensor_alpha, tensor_x)
a = a + tensor_bias1
print(a)
z = F.sigmoid(a)
print(z)
b = torch.mm(tensor_beta ,z)
b = b + tensor_bias2
print(b)
y_pred = torch.exp(b) / torch.sum( torch.exp(b) )
print(y_pred)
loss = -torch.sum(tensor_y * torch.log(y_pred))
print(loss)
loss.backward()
tensor_alpha = tensor_alpha - tensor_alpha.grad
print(tensor_alpha)
tensor_beta = tensor_beta - tensor_beta.grad
print(tensor_beta)
tensor_bias1 = tensor_bias1 - tensor_bias1.grad
print(tensor_bias1)
tensor_bias2 = tensor_bias2 - tensor_bias2.grad
print(tensor_bias2)


tensor([[2.],
        [7.],
        [8.],
        [2.]], dtype=torch.float64, grad_fn=<ThAddBackward>)
tensor([[0.8808],
        [0.9991],
        [0.9997],
        [0.8808]], dtype=torch.float64, grad_fn=<SigmoidBackward>)
tensor([[2.7604],
        [3.6430],
        [4.5226]], dtype=torch.float64, grad_fn=<ThAddBackward>)
tensor([[0.1082],
        [0.2615],
        [0.6303]], dtype=torch.float64, grad_fn=<DivBackward1>)
tensor(1.3412, dtype=torch.float64, grad_fn=<NegBackward>)
tensor([[ 0.8676,  1.8676, -3.0000,  0.0000,  0.8676, -3.1324],
        [ 2.9986,  0.9986,  2.0000,  1.0000, -0.0014,  1.9986],
        [ 2.0005,  2.0005,  2.0000,  2.0000,  2.0005,  1.0005],
        [ 1.0775,  0.0775,  2.0000,  1.0000, -1.9225,  2.0775]],
       dtype=torch.float64, grad_fn=<ThSubBackward>)
tensor([[ 0.9047,  1.8919, -2.1082,  0.9047],
        [ 1.6505, -0.2622,  1.7382,  2.6505],
        [ 2.4449,  0.3703, -1.6301,  0.4449]],
       dtype=torch.float64, grad_fn=<ThSubBackward>)
tensor([[0.867

/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


In [6]:
a = torch.mm(tensor_alpha, tensor_x)
a = a + tensor_bias1
print(a)
z = F.sigmoid(a)
print(z)
b = torch.mm(tensor_beta ,z)
b = b + tensor_bias2
print(b)
y_pred = torch.exp(b) / torch.sum( torch.exp(b) )
print(y_pred)
loss = -torch.sum(tensor_y * torch.log(y_pred))
print(loss)

tensor([[1.3382],
        [6.9928],
        [8.0027],
        [2.3877]], dtype=torch.float64, grad_fn=<ThAddBackward>)
tensor([[0.7922],
        [0.9991],
        [0.9997],
        [0.9159]], dtype=torch.float64, grad_fn=<SigmoidBackward>)
tensor([[2.2198],
        [6.9492],
        [1.4544]], dtype=torch.float64, grad_fn=<ThAddBackward>)
tensor([[0.0087],
        [0.9872],
        [0.0041]], dtype=torch.float64, grad_fn=<DivBackward1>)
tensor(0.0129, dtype=torch.float64, grad_fn=<NegBackward>)


/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
